-- 05-1
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

-- 05-2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

-- 05-3
-- 집합 연산자 사용 X
SELECT *
FROM EMP
WHERE (DEPTNO = 20 OR DEPTNO = 30) AND SAL>2000;

-- 집합 연산자 사용
SELECT *
FROM EMP
WHERE DEPTNO IN (20, 30)
INTERSECT
SELECT *
FROM EMP
WHERE SAL >2000;

-- 05-4
SELECT *
FROM EMP
WHERE SAL < 2000 OR SAL >3000;

-- 05-5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND SAL NOT BETWEEN 1000 AND 2000;

-- 05-6
SELECT *
FROM EMP
WHERE COMM IS NULL AND MGR IS NOT NULL AND JOB IN ('MANAGER', 'CLERK') AND ENAME NOT LIKE '_L%';
